# Generated by Django 4.0.3 on 2022-03-04 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payload', models.TextField()),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NestedResource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nested_payload', models.TextField()),
                ('related_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drfSpectecularReproducer.resource')),
            ],
        ),
    ]
